Repository agflow/dockerfiles, pull requests merged in 2019-05, with the labels that each got.

#1 feat: add go with linters
  .travis.yml
  go-with-linters/Dockerfile
  go-with-linters/README.md
Labels: size/M

#3 feat: add sqlparse, sqlcheck and poppler
  poppler/Dockerfile
  poppler/README.md
  sqlcheck/Dockerfile
  sqlcheck/README.md
  sqlparse/Dockerfile
  sqlparse/README.md
Labels: size/S

#6 feat: add python with linters
  python-with-linters/Dockerfile
  python-with-linters/README.md
Labels: size/S

#7 feat: add bodyclose and revive for go
  go-with-linters/Dockerfile
  go-with-linters/README.md
Labels: size/XS

#8 feat: add docker drone yaml
  drone-yaml/Dockerfile
  drone-yaml/README.md
Labels: size/S

#10 chore: drop impi in favor goimports
  go-with-linters/Dockerfile
  go-with-linters/README.md
Labels: size/XS

#11 feat: add filename lint dockerfile
  flint/Dockerfile
  flint/README.md
Labels: size/M

#13 chore(flint): update to version 2.2.0
  flint/Dockerfile
Labels: size/XS

#14 feat: add slate
  slate/Dockerfile
  slate/README.md
  slate/entrypoint.sh
Labels: size/M
